//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TestEventSchemaModel", "FK_OrderItemDetails_OrderDetails", "OrderDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CQRS.DataAccess.OrderDetail), "OrderItemDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CQRS.DataAccess.OrderItemDetail), true)]

#endregion

namespace CQRS.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestEventSchemaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestEventSchemaEntities object using the connection string found in the 'TestEventSchemaEntities' section of the application configuration file.
        /// </summary>
        public TestEventSchemaEntities() : base("name=TestEventSchemaEntities", "TestEventSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestEventSchemaEntities object.
        /// </summary>
        public TestEventSchemaEntities(string connectionString) : base(connectionString, "TestEventSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestEventSchemaEntities object.
        /// </summary>
        public TestEventSchemaEntities(EntityConnection connection) : base(connection, "TestEventSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderDetail> OrderDetails
        {
            get
            {
                if ((_OrderDetails == null))
                {
                    _OrderDetails = base.CreateObjectSet<OrderDetail>("OrderDetails");
                }
                return _OrderDetails;
            }
        }
        private ObjectSet<OrderDetail> _OrderDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderIndex> OrderIndexes
        {
            get
            {
                if ((_OrderIndexes == null))
                {
                    _OrderIndexes = base.CreateObjectSet<OrderIndex>("OrderIndexes");
                }
                return _OrderIndexes;
            }
        }
        private ObjectSet<OrderIndex> _OrderIndexes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderItemDetail> OrderItemDetails
        {
            get
            {
                if ((_OrderItemDetails == null))
                {
                    _OrderItemDetails = base.CreateObjectSet<OrderItemDetail>("OrderItemDetails");
                }
                return _OrderItemDetails;
            }
        }
        private ObjectSet<OrderItemDetail> _OrderItemDetails;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderDetails(OrderDetail orderDetail)
        {
            base.AddObject("OrderDetails", orderDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderIndexes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderIndexes(OrderIndex orderIndex)
        {
            base.AddObject("OrderIndexes", orderIndex);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderItemDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderItemDetails(OrderItemDetail orderItemDetail)
        {
            base.AddObject("OrderItemDetails", orderItemDetail);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestEventSchemaModel", Name="OrderDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderDetail object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static OrderDetail CreateOrderDetail(global::System.Guid orderId, global::System.Int32 version, global::System.String name)
        {
            OrderDetail orderDetail = new OrderDetail();
            orderDetail.OrderId = orderId;
            orderDetail.Version = version;
            orderDetail.Name = name;
            return orderDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.Int32 _Version;
        partial void OnVersionChanging(global::System.Int32 value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestEventSchemaModel", "FK_OrderItemDetails_OrderDetails", "OrderItemDetail")]
        public EntityCollection<OrderItemDetail> OrderItemDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderItemDetail>("TestEventSchemaModel.FK_OrderItemDetails_OrderDetails", "OrderItemDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderItemDetail>("TestEventSchemaModel.FK_OrderItemDetails_OrderDetails", "OrderItemDetail", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestEventSchemaModel", Name="OrderIndex")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderIndex : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderIndex object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="orderName">Initial value of the OrderName property.</param>
        public static OrderIndex CreateOrderIndex(global::System.Guid orderId, global::System.String orderName)
        {
            OrderIndex orderIndex = new OrderIndex();
            orderIndex.OrderId = orderId;
            orderIndex.OrderName = orderName;
            return orderIndex;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderName
        {
            get
            {
                return _OrderName;
            }
            set
            {
                OnOrderNameChanging(value);
                ReportPropertyChanging("OrderName");
                _OrderName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderName");
                OnOrderNameChanged();
            }
        }
        private global::System.String _OrderName;
        partial void OnOrderNameChanging(global::System.String value);
        partial void OnOrderNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestEventSchemaModel", Name="OrderItemDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderItemDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderItemDetail object.
        /// </summary>
        /// <param name="orderItemId">Initial value of the OrderItemId property.</param>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        public static OrderItemDetail CreateOrderItemDetail(global::System.Guid orderItemId, global::System.Guid orderId, global::System.Guid productId, global::System.String productName)
        {
            OrderItemDetail orderItemDetail = new OrderItemDetail();
            orderItemDetail.OrderItemId = orderItemId;
            orderItemDetail.OrderId = orderId;
            orderItemDetail.ProductId = productId;
            orderItemDetail.ProductName = productName;
            return orderItemDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderItemId
        {
            get
            {
                return _OrderItemId;
            }
            set
            {
                if (_OrderItemId != value)
                {
                    OnOrderItemIdChanging(value);
                    ReportPropertyChanging("OrderItemId");
                    _OrderItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderItemId");
                    OnOrderItemIdChanged();
                }
            }
        }
        private global::System.Guid _OrderItemId;
        partial void OnOrderItemIdChanging(global::System.Guid value);
        partial void OnOrderItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Guid _ProductId;
        partial void OnProductIdChanging(global::System.Guid value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestEventSchemaModel", "FK_OrderItemDetails_OrderDetails", "OrderDetail")]
        public OrderDetail OrderDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderDetail>("TestEventSchemaModel.FK_OrderItemDetails_OrderDetails", "OrderDetail").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderDetail>("TestEventSchemaModel.FK_OrderItemDetails_OrderDetails", "OrderDetail").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OrderDetail> OrderDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderDetail>("TestEventSchemaModel.FK_OrderItemDetails_OrderDetails", "OrderDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OrderDetail>("TestEventSchemaModel.FK_OrderItemDetails_OrderDetails", "OrderDetail", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
