//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TestEventSchemaModel", "FK_OrderLine_Order", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Pariveda.Infrastructure.ReadModel.Order), "OrderLine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Pariveda.Infrastructure.ReadModel.OrderLine), true)]

#endregion

namespace Pariveda.Infrastructure.ReadModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestEventSchemaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestEventSchemaEntities object using the connection string found in the 'TestEventSchemaEntities' section of the application configuration file.
        /// </summary>
        public TestEventSchemaEntities() : base("name=TestEventSchemaEntities", "TestEventSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestEventSchemaEntities object.
        /// </summary>
        public TestEventSchemaEntities(string connectionString) : base(connectionString, "TestEventSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestEventSchemaEntities object.
        /// </summary>
        public TestEventSchemaEntities(EntityConnection connection) : base(connection, "TestEventSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderLine> OrderLines
        {
            get
            {
                if ((_OrderLines == null))
                {
                    _OrderLines = base.CreateObjectSet<OrderLine>("OrderLines");
                }
                return _OrderLines;
            }
        }
        private ObjectSet<OrderLine> _OrderLines;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderLines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderLines(OrderLine orderLine)
        {
            base.AddObject("OrderLines", orderLine);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestEventSchemaModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="orderName">Initial value of the OrderName property.</param>
        public static Order CreateOrder(global::System.Guid orderId, global::System.String orderName)
        {
            Order order = new Order();
            order.OrderId = orderId;
            order.OrderName = orderName;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderName
        {
            get
            {
                return _OrderName;
            }
            set
            {
                OnOrderNameChanging(value);
                ReportPropertyChanging("OrderName");
                _OrderName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderName");
                OnOrderNameChanged();
            }
        }
        private global::System.String _OrderName;
        partial void OnOrderNameChanging(global::System.String value);
        partial void OnOrderNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestEventSchemaModel", "FK_OrderLine_Order", "OrderLine")]
        public EntityCollection<OrderLine> OrderLines
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderLine>("TestEventSchemaModel.FK_OrderLine_Order", "OrderLine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderLine>("TestEventSchemaModel.FK_OrderLine_Order", "OrderLine", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestEventSchemaModel", Name="OrderLine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderLine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderLine object.
        /// </summary>
        /// <param name="orderLineId">Initial value of the OrderLineId property.</param>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        public static OrderLine CreateOrderLine(global::System.Guid orderLineId, global::System.Guid orderId, global::System.Guid productId, global::System.String productName)
        {
            OrderLine orderLine = new OrderLine();
            orderLine.OrderLineId = orderLineId;
            orderLine.OrderId = orderId;
            orderLine.ProductId = productId;
            orderLine.ProductName = productName;
            return orderLine;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderLineId
        {
            get
            {
                return _OrderLineId;
            }
            set
            {
                if (_OrderLineId != value)
                {
                    OnOrderLineIdChanging(value);
                    ReportPropertyChanging("OrderLineId");
                    _OrderLineId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderLineId");
                    OnOrderLineIdChanged();
                }
            }
        }
        private global::System.Guid _OrderLineId;
        partial void OnOrderLineIdChanging(global::System.Guid value);
        partial void OnOrderLineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Guid _ProductId;
        partial void OnProductIdChanging(global::System.Guid value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestEventSchemaModel", "FK_OrderLine_Order", "Order")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TestEventSchemaModel.FK_OrderLine_Order", "Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TestEventSchemaModel.FK_OrderLine_Order", "Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TestEventSchemaModel.FK_OrderLine_Order", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("TestEventSchemaModel.FK_OrderLine_Order", "Order", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
