ALTER TABLE [dbo].[OrderLine]
    ADD CONSTRAINT [PK_OrderLine] PRIMARY KEY CLUSTERED ([OrderLineId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

